# Generated by Django 4.0.2 on 2022-02-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video',
            field=models.ManyToManyField(to='base.Video'),
        ),
    ]
