# Generated by Django 4.0.2 on 2022-02-06 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_episode_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
