# Generated by Django 4.0.2 on 2022-02-06 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_episode_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshows',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
